name: Sync mirror

on:
  push:
    branches:
      - '*'

jobs:
  mirror:
    if: github.repository == 'luis-noeda/test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Sync mirror
        env:
          MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          git clone --mirror "https://github.com/${{ github.repository }}.git" repo.git
          cd repo.git
          git push --mirror "https://x-access-token:${MIRROR_TOKEN}@github.com/luis-noeda/test-2.git"
